### ISSUE TITLE
Como jugador quiero que haya un menú principal

### ISSUE THREAD

**Issue by andrea-aparicio-lopez** [Proyectos1-FDI-UCM/c2324-Grupo03#104]
Funcionalidades del menú (crear tasks):
- [ ] Reanudar partida guardada
https://github.com/orgs/Proyectos1-FDI-UCM/projects/24/views/2?filterQuery=milestone%3A%22Hito+2%22+&sliceBy%5Bvalue%5D=UI&pane=issue&itemId=56618002
- [x] Reiniciar partida
https://github.com/orgs/Proyectos1-FDI-UCM/projects/24/views/2?filterQuery=milestone%3A%22Hito+2%22+&sliceBy%5Bvalue%5D=UI&pane=issue&itemId=56620391
- [ ] Ajustes
https://github.com/orgs/Proyectos1-FDI-UCM/projects/24/views/2?filterQuery=milestone%3A%22Hito+2%22+&sliceBy%5Bvalue%5D=UI&pane=issue&itemId=56620613

**Comment by MaEduardaB** [comment]
Hay menu pero los butones no tienen funcion aun
