### ISSUE TITLE
Como jugador quiero poder controlar al personaje desde mi teclado

### ISSUE THREAD

**Issue by marco-1337** [Proyectos1-FDI-UCM/c2324-Grupo03#11]
La parte de input de las acciones del personaje está ya toda creada.
Falta que estén los scripts de esas acciones para poder conectarlo

**Comment by andrea-aparicio-lopez** [comment]
Blink, Move y Look están

**Comment by andrea-aparicio-lopez** [comment]
El ataque está tmb. Estoy con las interacciones
