### ISSUE TITLE
No se debe poder construir en la noche en la build

### ISSUE THREAD

**Issue by marco-1337** [Proyectos1-FDI-UCM/c2324-Grupo03#172]

**Comment by andrea-aparicio-lopez** [comment]
Creo que esto era porque iba mal el ciclo dia/noche, en teoría era de día pero se ponía la luz de noche, de ahí que se pudiera interactuar y construir

**Comment by andrea-aparicio-lopez** [comment]
Nada era un error de código, yasta solucionado
