### ISSUE TITLE
BUGS ENEMIGOS

### ISSUE THREAD

**Issue by MaEduardaB** [Proyectos1-FDI-UCM/c2324-Grupo03#180]
- [ ] Spawnean enemigos de día
- [x] Las partículas cianes y magentas te spoilean la posición de los enemigos (no se ocultan si están fuera del FOV) 
- [x] Los enemigos se clippean entre ellos → habilitar colisiones entre ellos para evitarlo (Maria - creo que ya esta, necesito que alguien pruebe)
- [x] Los enemigos se atascan en las paredes.
- [x] Los enemigos salen siempre de un solo spawner.

**Comment by andrea-aparicio-lopez** [comment]
Creo que es problema de los estados de juego, que no se hace correctamente la transición a día. De momento cierro esta issue, si vemos que el problema es de los spawners la reabrimos
