### ISSUE TITLE
BUGS DIVERSOS

### ISSUE THREAD

**Issue by MaEduardaB** [Proyectos1-FDI-UCM/c2324-Grupo03#186]
- [x] Estatua y placeholder demasiado cerca, al interactuar abre los dos menús.
- [ ] Se deja de escuchar música a partir de la Noche 3
- [x] Dar utilidad a los cristales cianes y magentas

**Comment by andrea-aparicio-lopez** [comment]
Puesto que no se puede llegar a la noche 3, cierro esta issue. Si cuando los bugs de flujo de juego estén arreglados persiste este error, abrimos una bug issue
