### ISSUE TITLE
Como enemigo quiero poder ser generado

### ISSUE THREAD

**Issue by marco-1337** [Proyectos1-FDI-UCM/c2324-Grupo03#22]

**Comment by marco-1337** [comment]
Tal vez haya que implementar un manager de generación de enemigos

**Comment by MaEduardaB** [comment]
Cree un Manager de spawners, pero aun no esta completo. El sistema de waves no puede probar porque aun no podemos matar enemigos

**Comment by marco-1337** [comment]
Los enemigos pueden ser generados, falta refactor para las waves pero como tal la mecanica de spawn está
