### ISSUE TITLE
[BORRAR]

### ISSUE THREAD

**Issue by marco-1337** [Proyectos1-FDI-UCM/c2324-Grupo03#25]
Implementar nav mesh

**Comment by MaEduardaB** [comment]
Hice el navmesh pero solo sigue al personaje, tendremos que hacer cálculos para saber si esta mas cerca un pilar o el player, y que enfoque de acuerdo con sus características definidas en el gdd.

**Comment by marco-1337** [comment]
Tarea subdivida debido a demasiada carga
