### ISSUE TITLE
Como altar quiero poder ser reparado únicamente si mis respectivos placeholders especiales contienen una defensa

### ISSUE THREAD

**Issue by marco-1337** [Proyectos1-FDI-UCM/c2324-Grupo03#41]
Requisitos
- [x] Hay placeholders especiales

Tareas

Los altares deben registrar/tener serializado de antes sus respectivos placeholders especiales:

**Comment by MaEduardaB** [comment]
Los altares tiene sus respectivos placeholders y se reparan cuando los placeholders tienen defensa
