### ISSUE TITLE
Como recurso quiero poder ser recogido por el personaje

### ISSUE THREAD

**Issue by marco-1337** [Proyectos1-FDI-UCM/c2324-Grupo03#49]
REQUISITOS
- [x] Existencia del inventario del personaje que almacene el numero de recursos recogidos.
https://github.com/orgs/Proyectos1-FDI-UCM/projects/24/views/2?filterQuery=recurso&pane=issue&itemId=53601364
- [x] Los enemigos necesitan soltar recursos
https://github.com/orgs/Proyectos1-FDI-UCM/projects/24/views/2?sliceBy%5Bvalue%5D=RECURSOS&pane=issue&itemId=56073801

TAREAS
- [x] Crear el gameObject del recurso, box/circle collider2D para recogerlo, convertirlo en prefab.
https://github.com/orgs/Proyectos1-FDI-UCM/projects/24/views/2?sliceBy%5Bvalue%5D=RECURSOS&pane=issue&itemId=56016394
- [x] Dentro de ese prefab del recurso implementar un circle collider2D como campo de atracción que reaccione con el personaje.
https://github.com/orgs/Proyectos1-FDI-UCM/projects/24/views/2?sliceBy%5Bvalue%5D=RECURSOS&pane=issue&itemId=56018469
- [x] El personaje recoge el prefab del recurso y lo destruye.
https://github.com/orgs/Proyectos1-FDI-UCM/projects/24/views/2?sliceBy%5Bvalue%5D=RECURSOS&pane=issue&itemId=56018913
- [x] El prefab del recurso se registra en el HUD del personaje, sumando un cristal.
https://github.com/orgs/Proyectos1-FDI-UCM/projects/24/views/2?sliceBy%5Bvalue%5D=RECURSOS&pane=issue&itemId=56018992

**Comment by StardustAsher** [comment]
El personaje no debería de poder recoger minerales cuando está muerto.

**Comment by StardustAsher** [comment]
Poner un límite en 99 minerales (Cuando llegue ahí que no se puedan sumar más)

**Comment by MaEduardaB** [comment]
Hay un limite
