### ISSUE TITLE
Como personaje quiero tener la capacidad de hacer blink

### ISSUE THREAD

**Issue by marco-1337** [Proyectos1-FDI-UCM/c2324-Grupo03#7]

**Comment by Ikerjum** [comment]
A la hora de hacer blink haría falta un pequeño momento de invulnerabilidad (desactivar el collider que se encarga de recibir el daño) al hacer el desplazamiento, para que el gameplay no sea tan preciso y sea cómodo para el jugador.

**Comment by andrea-aparicio-lopez** [comment]
Hay que crear una hitbox (con su propio collider) para el player, y eso es lo que se desactiva temporalmente
